remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
# Custom CSS
assets:
  css: "assets/css/style.css"

title: "CreatingTimeCourse"
description: "PowerShell Training: Creating Time"
author: "John Doe"
keywords: "PowerShell, automation, scripting"
